Cherry pick of 5fead1bccb1c6fa89c1975f262f5c5707b9ce847 failed
stdout:
Auto-merging extensions/odoo_theme/static/js/menu.js
CONFLICT (content): Merge conflict in extensions/odoo_theme/static/js/menu.js

stderr:
20:06:36.396507 git.c:455               trace: built-in: git cherry-pick 5fead1bccb1c6fa89c1975f262f5c5707b9ce847
error: could not apply 5fead1bc... [IMP] odoo_theme: scroll the active menu entry into view
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: